update
AndreiBakhtinov/211123 pull request #18
Opened 2024-03-26 13:29 UTC by SmolnikNata

2024-04-16 11:20 UTC, Albina757 approved these changes

2024-04-16 11:20 UTC, SuesmairT reviewed
Завтра посмотрю

2024-04-16 11:22 UTC, SuesmairT requested changes
внести правки

2024-04-16 11:22 UTC, Julia1387 approved these changes

2024-04-16 11:24 UTC, RinasAlex reviewed
комментарий

2024-04-16 11:24 UTC, VoytovychM approved these changes

2024-04-16 11:25 UTC, AnnaDubinets approved these changes

2024-04-16 11:26 UTC, IrynaKosiak7 reviewed
Принят

2024-04-16 11:28 UTC, FartushkoY approved these changes

2024-04-16 11:38 UTC, Albina757 approved these changes

2024-04-16 11:39 UTC, RinasAlex approved these changes

2024-04-16 11:39 UTC, IrynaKosiak7 approved these changes
готово, спасибо

2024-04-16 11:42 UTC, SuesmairT approved these changes

2024-04-18 10:27 UTC, GroismanV approved these changes

2024-04-18 10:28 UTC, SuesmairT approved these changes

2024-04-18 10:29 UTC, IrynaKosiak7 reviewed
+

2024-04-18 10:29 UTC, GroismanV approved these changes

2024-04-18 10:29 UTC, Albina757 approved these changes

2024-04-18 10:29 UTC, GroismanV approved these changes

2024-04-18 10:30 UTC, AnnaDubinets approved these changes

2024-04-18 10:30 UTC, GroismanV approved these changes

2024-04-18 10:30 UTC, Albina757 approved these changes

2024-04-18 10:30 UTC, AnnaDubinets approved these changes

2024-04-18 10:30 UTC, Albina757 approved these changes

2024-04-18 10:30 UTC, VoytovychM approved these changes

2024-04-18 10:31 UTC, VoytovychM approved these changes

2024-04-18 10:31 UTC, merged